package com.aem.genericutilities;

/**
 * Here all the type of exception needs to be declared
 * 
 * @author mkarthik
 * 
 */
public enum Exceptions {
	NULL_URL_EXCEPTION, INVALID_URL_EXCEPTION, NULL_WEBDRIVER_EXCEPTION, SOURCE_DESTINATION_VALUES_NULL_EXCEPTION, INVALID_LOCATOR_TYPE_EXCEPTION, LOCATOR_VALUE_NULL_EXCEPTION, COULD_NOT_LOCATE_ELEMENT_EXCEPTION, NULL_VALUE_PASSED_EXCEPTION, LOCATOR_FORMAT_EXCEPTION, COULD_NOT_FIND_LOCATOR_FROM_REPOSITORY, INVALID_NUMBER_OF_VALUES, ALERT_NOT_AVAILABLE, NO_TEXT_FOUND, INVALID_VALUES_SENT_AS_PARAMETER, NAVIGATION_EXCEPTION, NO_SUCH_WINDOWID_EXISTS, COULD_NOT_FIND_UNIQUE_ELEMENT, By_is_null
}
